name: 'Retrigger Repository Webhooks'
description: 'This action allows to retrigger webhooks for a repository'
author: 'gateixeira'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  token:
    description: 'GitHub access token'
    required: true
  repo:
    description: 'Repository name'
    required: true
  owner:
    description: 'Repository owner'
    required: true
  last_redelivery_variable_name:
    description: 'The name of the variable that will store the last redelivery timestamp'
    required: true
  webhook_id:
    description: 'The ID to filter for a specific webhook'
    required: false
  base_url:
    description: 'The base URL for an Enterprise Server instance'
    required: false
runs:
  using: node20
  main: dist/index.js
